site_name: MonsterLifeServer：運営方針リポジトリ
site_url: https://operation-policy.mlserver.xyz/
copyright: '© 2024 MonsterLifeServer'
theme:
    name: material
    language: ja
nav:
    - Home: 'index.md'
    - '運営方針':
        - '1. 配信について': 'operation-policy/stream.md'